#ifndef MAIN_H
#define MAIN_H

#include <avr/cpufunc.h>

#define TICKS_PER_USEC F_CPU/1000000UL
#define US(n) n*(TICKS_PER_USEC)

#define TWO_NOPS() _NOP(); _NOP()
#define TEN_NOPS() TWO_NOPS(); TWO_NOPS(); TWO_NOPS(); TWO_NOPS(); TWO_NOPS()
#define ONEHUNDRED_NOPS() TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS()
#define FORTYTWO_NOPS() TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TEN_NOPS(); TWO_NOPS()
#define ONEHUNDRED_AND_TEN_NOPS() ONEHUNDRED_NOPS(); TEN_NOPS()

#endif // MAIN_H
